name: hemodynamics
channels:
  - conda-forge
dependencies:
  - python=3.10 
  - tensorflow=2.14.0  
  - cudatoolkit=11.8 
  - cudnn=8.9 
  - numpy 
  - matplotlib  
  - scipy 
  - h5py 
  - scikit-learn  
  - absl-py  
  - astunparse  
  - gast  
  - protobuf 
  - grpcio 
  - google-auth  
  - google-auth-oauthlib 
  - pillow 
  - markdown  
  - werkzeug  
  - jinja2  
  - pip  
