name: hemodynamics
channels:
  - conda-forge
dependencies:
  - python=3.9.19
  - tensorflow=2.14.0
  - tensorflow-gpu=2.14.0
  - tensorflow-estimator=2.14.0
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - numpy=1.26.4
  - matplotlib=3.8.4
  - scipy=1.13.0
  - h5py=3.11.0
  - scikit-learn=1.4.2
  - absl-py=2.1.0
  - astunparse=1.6.3
  - gast=0.5.4
  - protobuf=4.21.12
  - grpcio=1.54.3
  - google-auth=2.29.0
  - google-auth-oauthlib=1.0.0
  - pillow=10.3.0
  - markdown=3.6
  - werkzeug=3.0.3
  - jinja2=3.1.2
